### ISSUE TITLE
Technical Specification: Nut Blog Platform

### ISSUE THREAD

**Issue by wbornor** [wbornor/splaysh#2]
# Technical Specification: Nut Blog Platform

## 1. Overview

This document outlines the technical specifications for a blog platform that categorizes posts by type (called "Nuts"). The platform will be optimized for AWS free tier usage while maintaining a modern, scalable architecture.

### 1.1 Goals

- Create a serverless blog platform with minimal AWS costs
- Support different content types through a flexible data model
- Enable infinite scroll with pagination
- Allow filtering by content type
- Implement infrastructure as code using Terraform
- Automate deployment using GitHub Actions

### 1.2 Non-Goals

- Complex user authentication (will use simple authentication mechanism)
- Mobile application (will focus on responsive web design)
- Real-time features (comments, live updates)

### 2.1 High-Level Architecture

The architecture prioritizes AWS free tier services with a serverless approach to minimize costs while maintaining scalability and performance.

```
┌─────────────────┐     ┌─────────────────┐     ┌─────────────────┐
│                 │     │                 │     │                 │
│  GitHub Repo    │────▶│  GitHub Actions │────▶│  AWS Services   │
│                 │     │                 │     │                 │
└─────────────────┘     └─────────────────┘     └─────────────────┘
                                                         │
                                                         ▼
┌─────────────────┐                           ┌─────────────────┐
│                 │                           │                 │
│     Client      │◀──────────────────────────│  S3 Hosted      │
│     Browser     │                           │  Static Site    │
│                 │                           │                 │
└─────────────────┘                           └─────────────────┘
        │                                              ▲
        │                                              │
        ▼                                              │
┌─────────────────┐     ┌─────────────────┐     ┌─────────────────┐
│                 │     │                 │     │                 │
│ CloudFront CDN  │────▶│ API Gateway     │────▶│ Lambda + FastAPI│
│                 │     │                 │     │                 │
└─────────────────┘     └─────────────────┘     └─────────────────┘
                                                         │
                                                         ▼
                                                ┌─────────────────┐
                                                │                 │
                                                │   DynamoDB      │
                                                │                 │
                                                └─────────────────┘
```

#### 2.2.1 Frontend
- Single-page application (SPA) built with HTML, CSS, and JavaScript
- Static assets hosted on S3 and served via CloudFront
- Client-side data fetching with pagination support
- Responsive design for all device sizes

#### 2.2.2 Backend
- Primary content delivery through static JSON files hosted on S3
- Secondary option: FastAPI Python backend deployed as AWS Lambda function
- API Gateway for request routing
- DynamoDB for data storage

#### 2.2.3 Infrastructure
- Terraform for infrastructure as code
- GitHub Actions for CI/CD pipeline
- CloudFront for content delivery network (CDN)

### 3.1 AWS Infrastructure Components

| Service | Purpose | Free Tier Coverage |
|---------|---------|-------------------|
| S3 | Static web hosting, JSON data storage | 5GB storage, 20,000 GET, 2,000 PUT requests |
| CloudFront | CDN, SSL termination | 1TB data transfer out, 10,000,000 HTTP/HTTPS requests |
| DynamoDB | Data storage | 25GB storage, 25 WCU, 25 RCU |
| Lambda | API handlers | 1M free requests, 400,000 GB-seconds |
| API Gateway | API routing | 1M API calls |

### 3.2 Data Storage Approaches

We'll implement two approaches and evaluate which is more cost-effective:

#### 3.2.1 Static JSON Approach
- Generate static JSON files during build process
- Store files in S3 with chunked, paginated directory structure
- Client fetches data incrementally as needed
- Pros: Simplest, lowest cost, no backend needed, efficient loading
- Cons: Updates require rebuilding and redeploying
- Optimization: Implement time-based and ID-based chunking for efficient retrieval

#### 3.2.2 DynamoDB + Lambda Approach
- Store data in DynamoDB
- Access via Lambda functions + FastAPI
- Client interacts with API endpoints
- Pros: Dynamic content, easier updates
- Cons: Slightly higher complexity and potential cost

Both approaches will be implemented with Terraform, and performance metrics will determine the final selection.

### 3.3 Data Model

The data model will support the various "Nut" content types, each with its own schema:

```json
{
  "id": "string",
  "type": "string",  // "talknut", "projectnut", "photonut", "medianut", "analnut"
  "createdAt": "timestamp",
  "updatedAt": "timestamp",
  "title": "string",
  "content": {
    // Schema varies by type
  }
}
```

##### TalkNut
```json
{
  "content": {
    "body": "string"  // Free-form text
  }
}
```

##### ProjectNut
```json
{
  "content": {
    "description": "string",
    "status": "string",
    "links": ["string"],
    "tags": ["string"]
  }
}
```

##### PhotoNut
```json
{
  "content": {
    "albumId": "string",  // Google Photos Album ID
    "description": "string",
    "coverImageUrl": "string"
  }
}
```

##### MediaNut
```json
{
  "content": {
    "imageUrl": "string",
    "description": "string",
    "mediaType": "string",  // "book", "video", etc.
    "externalLink": "string"
  }
}
```

##### AnalNut
```json
{
  "content": {
    "a": "string",
    "b": "string",
    "x": "string",
    "y": "string",
    "explanation": "string"
  }
}
```

### 3.4 API Endpoints

If using the DynamoDB + Lambda approach, the following API endpoints will be implemented:

#### 3.4.1 GET /api/posts
- Query parameters:
  - `type`: Filter by nut type
  - `limit`: Number of posts to return (default: 10)
  - `nextToken`: Pagination token

#### 3.4.2 GET /api/posts/{id}
- Retrieve a specific post by ID

#### 3.4.3 Authentication-protected endpoints
- POST /api/posts
- PUT /api/posts/{id}
- DELETE /api/posts/{id}

### 3.5 Frontend Implementation

The frontend will be a simple SPA with the following key features:

- Infinite scroll for post browsing
- Filtering by nut type
- Responsive design using CSS Grid and Flexbox
- Minimal JavaScript dependencies to reduce bundle size
- Client-side rendering of different post types

### 4.1 Infrastructure Setup

1. Create Terraform configurations for:
   - S3 bucket for static web hosting
   - CloudFront distribution
   - DynamoDB table(s)
   - IAM roles and policies
   - Lambda functions (if needed)
   - API Gateway (if needed)

2. Set up GitHub repository structure:
   ```
   ├── .github/
   │   └── workflows/
   │       ├── deploy-infra.yml
   │       └── deploy-app.yml
   ├── terraform/
   │   ├── main.tf
   │   ├── variables.tf
   │   ├── outputs.tf
   │   └── modules/
   ├── frontend/
   │   ├── src/
   │   ├── public/
   │   └── package.json
   ├── backend/ (if needed)
   │   ├── app/
   │   ├── requirements.txt
   │   └── Dockerfile
   └── README.md
   ```

### 4.2 Static JSON Approach Implementation

1. Create script to generate JSON files from DynamoDB or other source
2. Organize files in chunked, paginated directory structure:
   ```
   /data/
     /posts/
       /index.json      # Metadata with pagination info & counts
       /talknut/
         /index.json    # Talknut metadata
         /page_1.json   # 10-20 posts per file
         /page_2.json
         /page_3.json
         ...
         /year/
           /2025/
             /index.json
             /page_1.json
             ...
           /2024/
             ...
       /projectnut/
         /index.json    # Projectnut metadata
         /page_1.json   # 10-20 posts per file
         ...
       /photonut/
         ...
       /medianut/
         ...
       /analnut/
         ...
       /by_id/
         /1000-1999/    # Group by ID ranges
           /{id}.json   # Individual post data
         /2000-2999/
           /{id}.json
         ...
   ```
3. Implement client-side JavaScript to fetch and render JSON data
4. Add infinite scroll and filtering logic

### 4.3 DynamoDB + Lambda Approach Implementation

1. Create DynamoDB table with appropriate indexes
2. Implement FastAPI application with required endpoints
3. Deploy as Lambda function
4. Set up API Gateway integration
5. Implement client-side code to interact with API

### 4.4 GitHub Actions CI/CD

1. Create workflow for Terraform infrastructure deployment
   ```yaml
   name: Deploy Infrastructure
   on:
     push:
       branches: [main]
       paths: ['terraform/**']
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: hashicorp/setup-terraform@v2
         - name: Terraform Init
           run: terraform init
           working-directory: ./terraform
         - name: Terraform Apply
           run: terraform apply -auto-approve
           working-directory: ./terraform
           env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   ```

2. Create workflow for application deployment
   ```yaml
   name: Deploy Application
   on:
     push:
       branches: [main]
       paths: ['frontend/**', 'backend/**']
   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
             node-version: 16
         - name: Build Frontend
           run: |
             cd frontend
             npm install
             npm run build
         - name: Deploy to S3
           uses: jakejarvis/s3-sync-action@master
           with:
             args: --delete
           env:
             AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             SOURCE_DIR: 'frontend/dist'
   ```

## 5. Google Photos Integration Migration

To migrate from Flickr albums to Google Photos albums:

1. Create a Google API project and enable Google Photos API
2. Implement OAuth 2.0 authentication for Google Photos
3. Create Lambda function to fetch album data from Google Photos API
4. Store album metadata and image URLs in DynamoDB/JSON
5. Update the frontend to render Google Photos content

### 6.1 AWS Free Tier Usage Optimization

- S3: Store only essential data; compress images and assets
- DynamoDB: Use on-demand capacity mode to stay within free tier
- Lambda: Keep functions small and efficient
- CloudFront: Use caching effectively to reduce origin requests
- JSON Files: Implement efficient chunking and pagination to minimize data transfer

### 6.2 JSON File Optimization Strategies

- **Chunked Loading**: Break down large JSON files into smaller chunks (10-20 posts per file)
- **Pagination Metadata**: Include pagination details in index files for efficient navigation
- **Chronological Directories**: Organize files by year/month for time-based queries
- **ID Range Grouping**: Group individual post files by ID ranges for efficient lookup
- **Compression**: Enable gzip/Brotli compression in CloudFront for smaller file transfers
- **Cache-Control Headers**: Optimize caching for static files

### 6.2 Cost Comparison

| Approach | Pros | Cons | Estimated Monthly Cost |
|----------|------|------|------------------------|
| Static JSON | Simplest, fully serverless | Less flexible for updates | $0-1 |
| DynamoDB + Lambda | More dynamic, easier updates | Slightly higher complexity | $0-3 |

Both approaches can operate within the AWS free tier with proper optimization.

### 7.1 Infrastructure Testing
- Validate Terraform configurations
- Test AWS resource provisioning
- Verify permissions and access controls

### 7.2 Functional Testing
- Test content creation and retrieval
- Validate pagination and filtering
- Test Google Photos integration

### 7.3 Performance Testing
- Measure page load times
- Evaluate infinite scroll performance
- Test CDN caching efficiency

### 8.1 CloudWatch Metrics to Monitor
- S3 request counts
- Lambda invocations and duration
- DynamoDB consumed capacity
- CloudFront requests and data transfer

### 8.2 Alerts
- Set up alerts for approaching free tier limits
- Monitor for errors in Lambda functions
- Track failed deployments

### 9.1 Data Protection
- Enable S3 bucket encryption
- Configure appropriate CORS policies
- Implement least privilege IAM policies

### 9.2 API Security
- Use API keys for protected endpoints
- Implement rate limiting
- Consider AWS WAF for additional protection

## 10. Future Enhancements

- Add tagging functionality across all post types
- Implement search capabilities
- Support for additional content types
- User authentication for comments

## 11. Conclusion

This tech spec outlines a cost-effective approach to implement the Nut Blog Platform using AWS free tier services. By leveraging static hosting with optional API capabilities, we can create a scalable, maintainable solution that minimizes ongoing costs while meeting all functional requirements.

The recommended implementation is to start with the Static JSON approach for its simplicity and lowest cost, with the option to migrate to the DynamoDB + Lambda approach if more dynamic functionality is needed in the future.
